import { IPointChangeHistoryViewModel } from "./interfaces";

export const pointChangeHistories: IPointChangeHistoryViewModel[] = [
  {
    code: "LVSĐ_20250715_001",
    updatedDate: "2025-07-15",
    updatedTime: "10:30:45 AM",
    executor: "GV.Nguyễn Văn A",
    studentCode: "HS00123",
    studentName: "Nguyễn Thị Hằng",
    subject: "Toán",
    scoreType: "Điểm 1 gốc",
    value: 7.5,
    reason: "Nhập điểm ban đầu cho bài kiểm tra 15 phút.",
  },
  {
    code: "LVSĐ_20250715_002",
    updatedDate: "2025-07-15",
    updatedTime: "10:32:00 AM",
    executor: "GV.Nguyễn Văn A",
    studentCode: "HS00123",
    studentName: "Nguyễn Thị Hằng",
    subject: "Toán",
    scoreType: "Điểm 1 sửa",
    value: 8.0,
    reason: "Sửa lỗi nhập liệu do gõ nhầm điểm gốc.",
  },
  {
    code: "LVSĐ_20250715_003",
    updatedDate: "2025-07-15",
    updatedTime: "10:35:10 AM",
    executor: "GV.Nguyễn Văn A",
    studentCode: "HS00456",
    studentName: "Trần Minh Đức",
    subject: "Văn",
    scoreType: "Điểm 1 gốc",
    value: 6.0,
    reason: "Nhập điểm ban đầu cho điểm miệng.",
  },
  {
    code: "LVSĐ_20250715_004",
    updatedDate: "2025-07-15",
    updatedTime: "10:37:00 AM",
    executor: "GV.Nguyễn Văn A",
    studentCode: "HS00456",
    studentName: "Trần Minh Đức",
    subject: "Văn",
    scoreType: "Điểm 1 sửa",
    value: 7.5,
    reason: "Cập nhật điểm sau khi học sinh trả lời thêm câu hỏi.",
  },
  {
    code: "LVSĐ_20250714_005",
    updatedDate: "2025-07-14",
    updatedTime: "15:00:20 PM",
    executor: "QLDT.Phạm Thị B",
    studentCode: "HS00789",
    studentName: "Lê Thanh Nga",
    subject: "Anh Văn",
    scoreType: "Điểm 1 gốc",
    value: 8.0,
    reason: "Nhập điểm gốc cho bài kiểm tra giữa kỳ.",
  },
  {
    code: "LVSĐ_20250714_006",
    updatedDate: "2025-07-14",
    updatedTime: "15:05:00 PM",
    executor: "QLDT.Phạm Thị B",
    studentCode: "HS00789",
    studentName: "Lê Thanh Nga",
    subject: "Anh Văn",
    scoreType: "Điểm 1 sửa",
    value: 9.0,
    reason: "Cập nhật điểm sau phúc khảo bài kiểm tra.",
  },
];
