import { IXemChiTietInfoViewModel } from "./IntellectualPropertyProfileButtonModal";
import { IIntellectualPropertyProfileInfoViewModel } from "./IntellectualPropertyProfileRead";

export const mockData: IIntellectualPropertyProfileInfoViewModel[] = [
  {
    msIp: "IP-SC-2023-001",
    tenIpSanPham: "Hệ thống quản lý chất thải thông minh",
    loaiHinhShtt: "Bằng sáng chế",
    chuSoHuu: "Trường Y",
    tacGiaNhoPhatMinh: "TS Minh Nguyen, K. An Trại",
    tinhTrangPhapLy: "Đã văn cấp bằng",
    ngayNopDon: "2023-03-01",
    ngayCapBang: "2024-12-20",
    thoiHanBaoHo: "20 năm",
    ngayHetHieuLuc: "2043-03-01",
    linhVucNganhHoc: "Khoa học Môi trường",
    quocGiaDangKy: "Việt Nam",
    duAnLienQuan: "DAHT-001",
  },
  {
    msIp: "IP-SC-2024-002",
    tenIpSanPham: "Thuật toán nhận dạng khuôn mặt bằng",
    loaiHinhShtt: "Bằng sáng chế",
    chuSoHuu: "Trường Y",
    tacGiaNhoPhatMinh: "GS Lan Phạm, K. Hùng Lê",
    tinhTrangPhapLy: "Đang thẩm định",
    ngayNopDon: "2024-01-10",
    ngayCapBang: "",
    thoiHanBaoHo: "",
    ngayHetHieuLuc: "",
    linhVucNganhHoc: "Công nghệ thông tin",
    quocGiaDangKy: "Lào",
    duAnLienQuan: "N/A (Nghiên cứu nội bộ)",
  },
  {
    msIp: "IP-CL-2023-001",
    tenIpSanPham: "Sách giáo trình “Cơ sở vật lý y sinh”",
    loaiHinhShtt: "Bản quyền tác giả",
    chuSoHuu: "Trường Y",
    tacGiaNhoPhatMinh: "PGS Hiếu Bùi",
    tinhTrangPhapLy: "Đã văn cấp bằng",
    ngayNopDon: "2023-09-05",
    ngayCapBang: "2024-02-15",
    thoiHanBaoHo: "Suốt đời tác giả + 75 năm",
    ngayHetHieuLuc: "",
    linhVucNganhHoc: "Y sinh học",
    quocGiaDangKy: "Campuchia",
    duAnLienQuan: "N/A",
  },
  {
    msIp: "IP-KDCN-2025-00",
    tenIpSanPham: "Thiết kế bình lọc nước thông minh",
    loaiHinhShtt: "Kiểu dáng công nghiệp",
    chuSoHuu: "Trường Y, Cty AquaTech",
    tacGiaNhoPhatMinh: "TS Nam Hoàng",
    tinhTrangPhapLy: "Đang nộp đơn",
    ngayNopDon: "2025-06-01",
    ngayCapBang: "",
    thoiHanBaoHo: "",
    ngayHetHieuLuc: "",
    linhVucNganhHoc: "Kỹ thuật Môi trường",
    quocGiaDangKy: "China",
    duAnLienQuan: "DAHT-003",
  },
  {
    msIp: "IP-NH-2024-001",
    tenIpSanPham: "“GreenChem” (Logo & Tên)",
    loaiHinhShtt: "Nhãn hiệu",
    chuSoHuu: "Trường Y",
    tacGiaNhoPhatMinh: "N/A",
    tinhTrangPhapLy: "Đang thẩm định",
    ngayNopDon: "2024-02-20",
    ngayCapBang: "",
    thoiHanBaoHo: "",
    ngayHetHieuLuc: "",
    linhVucNganhHoc: "Hóa học",
    quocGiaDangKy: "Taiwan",
    duAnLienQuan: "N/A (Thương mại hóa)",
  },
];


export const mockDataButtonXemChiTiet: IXemChiTietInfoViewModel[] = [
  {
      maBanGhiLichSu: "LTS-001",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Đang nộp đơn",
      ngayThayDoi: "01/03/2023",
      nguoiHeThongThayDoi: "Hệ thống (Đăng ký từ tóc giả)",
      moTaChiTietSuKien: "Hỗ trợ được tạo và nộp chính thức tại Cục SHTT.",
  },
  {
      maBanGhiLichSu: "LTS-002",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Đang thẩm định (Hình thức)",
      ngayThayDoi: "15/04/2023",
      nguoiHeThongThayDoi: "Hệ thống (Cán bộ IP)",
      moTaChiTietSuKien: "Cục SHTT đã chấp nhận đơn hợp lệ về hình thức.",
  },
  {
      maBanGhiLichSu: "LTS-003",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Đã công bố đơn",
      ngayThayDoi: "20/05/2023",
      nguoiHeThongThayDoi: "Hệ thống (Cán bộ IP)",
      moTaChiTietSuKien: "Đơn đã được công bố trên Công báo SHTT số 450.",
  },
  {
      maBanGhiLichSu: "LTS-004",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Đang thẩm định (Nội dung)",
      ngayThayDoi: "01/06/2023",
      nguoiHeThongThayDoi: "Hệ thống (Cán bộ IP)",
      moTaChiTietSuKien: "Bắt đầu giai đoạn thẩm định nội dung bởi Cục SHTT.",
  },
  {
      maBanGhiLichSu: "LTS-005",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Đã cấp văn bằng",
      ngayThayDoi: "20/12/2024",
      nguoiHeThongThayDoi: "Hệ thống (Cán bộ IP)",
      moTaChiTietSuKien: "Văn bằng bảo hộ đã được cấp.",
  },
  {
      maBanGhiLichSu: "LTS-006",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Đang hiệu lực",
      ngayThayDoi: "21/12/2024",
      nguoiHeThongThayDoi: "Hệ thống",
      moTaChiTietSuKien: "Bằng độc quyền sáng chế chính thức có hiệu lực.",
  },
  {
      maBanGhiLichSu: "LTS-007",
      maIpFk: "IP-SC-2023-001",
      tenIp: "Hệ thống quản lý chất thải thông minh",
      trangThaiPhapLyMoi: "Cần duy trì hiệu lực",
      ngayThayDoi: "01/03/2025",
      nguoiHeThongThayDoi: "Hệ thống (Nhắc nhở tự động)",
      moTaChiTietSuKien: "Sắp đến hạn nộp phí duy trì hiệu lực năm 3.",
  },
  {
      maBanGhiLichSu: "LTS-008",
      maIpFk: "IP-SC-2024-002",
      tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
      trangThaiPhapLyMoi: "Đang nộp đơn",
      ngayThayDoi: "10/01/2024",
      nguoiHeThongThayDoi: "Hệ thống (Đăng ký từ tóc giả)",
      moTaChiTietSuKien: "Hỗ trợ được tạo và nộp chính thức.",
  },
  {
      maBanGhiLichSu: "LTS-009",
      maIpFk: "IP-SC-2024-002",
      tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
      trangThaiPhapLyMoi: "Đang thẩm định (Hình thức)",
      ngayThayDoi: "25/02/2024",
      nguoiHeThongThayDoi: "Hệ thống (Cán bộ IP)",
      moTaChiTietSuKien: "Cục SHTT đã chấp nhận đơn hợp lệ về hình thức.",
  },
  {
      maBanGhiLichSu: "LTS-010",
      maIpFk: "IP-SC-2024-002",
      tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
      trangThaiPhapLyMoi: "Đang thẩm định (Nội dung)",
      ngayThayDoi: "01/04/2024",
      nguoiHeThongThayDoi: "Hệ thống (Cán bộ IP)",
      moTaChiTietSuKien: "Chuyển sang giai đoạn thẩm định nội dung.",
  },
  {
      maBanGhiLichSu: "LTS-011",
      maIpFk: "IP-SC-2024-002",
      tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
      trangThaiPhapLyMoi: "Yêu cầu sửa đổi đơn",
      ngayThayDoi: "15/05/2024",
      nguoiHeThongThayDoi: "Chuyển viên IP",
      moTaChiTietSuKien: "Có công văn của Cục SHTT yêu cầu sửa đổi mô tả.",
  },
]
