import { IF9_4_5ReadTrackProgress } from "./F9_4_5ReadTrackProgress"
import { IF9_4_5UpdateTrackProgressButtonModal } from "./F9_4_5UpdateTrackProgressButtonModal"
export const mockDataRead:IF9_4_5ReadTrackProgress[]=[
    {
        planCode: "KHTT2025001",
        editorialBoardCode: "BBGT2025001",
        suggestionCode: "GT2025001",
        suggestionCurriculumName: "Giáo trình Nguyên lý kế toán",
        dateOfPlan: "2025-08-15",
        estimateStartDateOfPlan: "2025-08-20",
        estimateEndDateOfPlan: "2026-03-30",
        planExecutioner: "Th.S Nguyễn Văn A (GV.12345)",
        planStatus: "Đang chờ duyệt",
        fileAttachment: "Xem file",
      },
      {
        planCode: "KHTT2025002",
        editorialBoardCode: "BBGT2025002",
        suggestionCode: "GT2025002",
        suggestionCurriculumName: "Giáo trình Phân tích Dữ liệu lớn",
        dateOfPlan: "2025-08-18",
        estimateStartDateOfPlan: "2025-08-25",
        estimateEndDateOfPlan: "2026-04-15",
        planExecutioner: "TS.Hoàng D(GV.99887)",
        planStatus: "Đã phê duyệt",
        fileAttachment: "Xem file",
      },
      {
        planCode: "KHTT2025003",
        editorialBoardCode: "BBGT2025003",
        suggestionCode: "GT2025004",
        suggestionCurriculumName: "Giáo trình Kinh tế Vĩ mô",
        dateOfPlan: "2025-08-20",
        estimateStartDateOfPlan: "2025-08-28",
        estimateEndDateOfPlan: "2026-05-30",
        planExecutioner: "PGS.Kim G (GV.44556)",
        planStatus: "Đang chờ duyệt",
        fileAttachment: "Xem file",
      },
]
export const mockDataReadModal:IF9_4_5UpdateTrackProgressButtonModal[]=[
    {
        phaseCode: "GD001",
        numberOfPhase: 1,
        phaseName: "Xây dựng Đề cương chi tiết",
        responsibleMember: "ThS.Nguyễn Văn A(GV.12345)",
        estimateStartDate: "2025-08-20",
        estimateEndDate: "2025-09-05",
        percentageOfCompletion:100,
        progressStatus: "Hoàn thành",
        actualEndDate: "2025-09-03",
        progressNote: "Đề cương đã được Ban Biên soạn thông qua",
        fileAttachment: "Xem file",
    },
    {
        phaseCode: "GD002",
        numberOfPhase: 2,
        phaseName: "Biên soạn bản thảo Chương 1-3",
        responsibleMember: "ThS.Trần Thị B(GV.67890)",
        estimateStartDate: "2025-09-06",
        estimateEndDate: "2025-10-30",
        percentageOfCompletion: 60,
        progressStatus: "Đang thực hiện",
        actualEndDate: "",
        progressNote: "Chương 1 và 2 đã hoàn thành bản nháp;Chương 3 đang triển khai nội dung",
        fileAttachment: "Xem file",
    },
    {
        phaseCode: "GD003",
        numberOfPhase: 3,
        phaseName: "Rà soát và chỉnh sửa nội bộ",
        responsibleMember: "ThS. Phạm C(GV.33445)",
        estimateStartDate: "2025-11-01",
        estimateEndDate: "2025-11-30",
        percentageOfCompletion: 0,
        progressStatus: "Chưa bắt đầu",
        actualEndDate: "",
        progressNote: "Chờ bản thảo Chương 1-3 hoàn thiện",
        fileAttachment: "Xem file",
    },
    {
        phaseCode: "GD004",
        numberOfPhase: 4,
        phaseName: "Gửi và Chờ Thẩm định",
        responsibleMember: "ThS.Nguyễn Văn A(GV.12345)",
        estimateStartDate: "2025-12-01",
        estimateEndDate: "2025-12-15",
        percentageOfCompletion: 0,
        progressStatus: "Chưa bắt đầu",
        actualEndDate: "",
        progressNote: "",
        fileAttachment: "Xem file",
    }
]
export const dataMockProgressStatus = [
    { value: "Chưa bắt đầu", label: "Chưa bắt đầu" },
    { value: "Đang thực hiện", label: "Đang thực hiện" },
    { value: "Chưa hoàn thành", label: "Chưa hoàn thành" },
    { value: "Hoàn thành", label: "Hoàn thành" },
    { value: "Tạm dừng", label: "Tạm dừng" },
    { value: "Hủy bỏ", label: "Hủy bỏ" },
]

