import { I_Class, I_ClassStudent } from "./interfaces";
import { ClassStatus } from "./utils/ClassStatusBadge";


export const mockData_ClassList: I_Class[] = [
  {
    code: "LD1",
    name: "Lập trình Web Cơ bản 1",
    homeroomTeacherName: "Trần Nhật Minh",
    schedule: "Thứ 2 & 5 (18:00-20:00)",
    room: "P.TD01",
    currentCapacity: 10,
    maxCapacity: 15,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD2A1",
    name: "Tiếng Anh Giao tiếp A1",
    homeroomTeacherName: "Nguyễn Thị Hải",
    schedule: "Thứ 2 & 4 (19:00-21:00)",
    room: "P.TD02",
    currentCapacity: 11,
    maxCapacity: 15,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD2A2",
    name: "Tiếng Anh Giao tiếp A2",
    homeroomTeacherName: "Lê Thị Quế",
    schedule: "Thứ 7 & CN (09:00-11:00)",
    room: "P.TD03",
    currentCapacity: 8,
    maxCapacity: 11,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD2B",
    name: "Giải tích Nâng cao",
    homeroomTeacherName: "Trần Thị Phương Thảo",
    schedule: "Thứ 3 & 5 (18:00-20:00)",
    room: "P.TD01",
    currentCapacity: 11,
    maxCapacity: 15,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD2C1",
    name: "Hóa học Đại cương",
    homeroomTeacherName: "Hoàng Thị Hương",
    schedule: "Thứ 6 (18:00-21:00)",
    room: "P.TD04",
    currentCapacity: 9,
    maxCapacity: 10,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD2C2",
    name: "Vật lý Nâng cao",
    homeroomTeacherName: "Trần Thị Quy",
    schedule: "Thứ 7 (14:00-17:00)",
    room: "P.TD05",
    currentCapacity: 7,
    maxCapacity: 10,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD3A",
    name: "Lịch sử Việt Nam",
    homeroomTeacherName: "Lê Thu Trang",
    schedule: "Thứ 2 & 4 (18:00-20:00)",
    room: "P.TD06",
    currentCapacity: 14,
    maxCapacity: 15,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD3B",
    name: "Kinh tế Vi mô",
    homeroomTeacherName: "Trần Trọng Thưởng",
    schedule: "Thứ 3 & 6 (18:00-20:00)",
    room: "P.TD07",
    currentCapacity: 13,
    maxCapacity: 15,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD3C",
    name: "Địa lý Tự nhiên",
    homeroomTeacherName: "Lê Thị Trường An",
    schedule: "Thứ 6 (17:00-19:00)",
    room: "P.TD08",
    currentCapacity: 9,
    maxCapacity: 11,
    status: ClassStatus.Active,
    isGraded: true,
  },
  {
    code: "LD3D",
    name: "Ngữ văn Hiện đại",
    homeroomTeacherName: "Trần Trọng Thưởng",
    schedule: "Chủ Nhật (09:00-12:00)",
    room: "P.TD09",
    currentCapacity: 10,
    maxCapacity: 11,
    status: ClassStatus.Active,
    isGraded: true,
  },
];

export const mockData_ClassStudent: I_ClassStudent[] = [
  {
    code: "CG23-01030",
    name: "Nguyễn Ngọc Trang Anh",
    parentPhone: "0974681988",
    studentStatus: 1,
    note: "Chưa làm",
    attendanceStatus: 1,
    originScore: 6,
    comment: "Thiếu bài",
  },
  {
    code: "CG23-01040",
    name: "Mẫn Vũ Minh Anh",
    parentPhone: "0974326882",
    studentStatus: 1,
    note: "",
    attendanceStatus: 2,
    originScore: null,
    editedScore: null,
    comment: 'bđTt, bđ, thiếu ý',
  },
  {
    code: "CG23-01153",
    name: "Nguyễn Quốc Minh Châu",
    parentPhone: "0962455208",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 8.5,
    comment: "Thiếu bài, tt, bđ, sai dấu",
    reward: 1,
  },
  {
    code: "CG24-01157",
    name: "Phạm Ngô Khánh Diệp",
    parentPhone: "0348496839",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 6.5,
    editedScore: null,
    comment: 'Thiếu TH, tt, bđ',
  },
  {
    code: "CG24-01067",
    name: "Phạm Hoàng Hải",
    parentPhone: "0348689937",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 6,
    comment: 'Thiếu bài',
  },
  {
    code: "CG23-01067",
    name: "Nguyễn Minh Hải",
    parentPhone: "0943458190",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 7.5,
    comment: 'tt, thiếu xđ hệ số',
    reward: 1,
  },
  {
    code: "CG23-01068",
    name: "Trần Bảo Hân",
    parentPhone: "0874510110",
    studentStatus: 2,
    note: "Chuyển từ 7B2 CG sang ngày 18/02/2025",
    attendanceStatus: 1,
    originScore: 8,
    comment: 'Tt, bđ, thiếu bài',
  },
  {
    code: "CG23-01069",
    name: "Đặng Gia Hân",
    parentPhone: "0985541333",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 4.5,
    editedScore: "S",
    comment: "Tt, bđ, kl sai",
  },
  {
    code: "CG23-00931",
    name: "Nguyễn Vân Huệ",
    parentPhone: "0974359966",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 8.5,
    comment: 'Thiếu bài',
  },
  {
    code: "CG23-00932",
    name: "Lê Thị K",
    parentPhone: "0943215447",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 7.0,
    comment: 'Tt, bđ, thiếu bài, thiếu kl',
  },
  {
    code: "CG23-00933",
    name: "Phạm Thị M",
    parentPhone: "0974359748",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 8.0,
    comment: 'Tt, bđ, t/c lũy thừa',
  },
  {
    code: "CG23-00934",
    name: "Trần Thị N",
    parentPhone: "0974359746",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 9.0,
    comment: 'Tt, bđ, thiếu bài',
  },
  {
    code: "CG23-00935",
    name: "Ngô Minh P",
    parentPhone: "0974359470",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 9.0,
    comment: 'Thiếu bài, tt',
  },
  {
    code: "CG23-00936",
    name: "Vũ Thị Q",
    parentPhone: "0974359471",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 7.0,
    comment: 'Xđ sai hệ số bđ, thiếu bài',
  },
  {
    code: "CG23-01037",
    name: "Đặng Văn R",
    parentPhone: "0974359492",
    studentStatus: 1,
    note: "",
    attendanceStatus: 1,
    originScore: 8.5,
    comment: 'Tt, bđ',
  }
];
