import { IAssignmentOfApprovalButtonModalInfoViewModel } from "./AssignmentOfApprovalButtonModal";
import { IAssignmentOfApprovalReadInfoViewModel } from "./AssignmentOfApprovalRead";


export const mockData: IAssignmentOfApprovalReadInfoViewModel[] = [
  {
      maCtTraoDoi: "CTTCB-2025-001",
      tenCtTraoDoi: "Chương trình Trao đổi SV Kỹ thuật",
      doiTacChinh: "Siemens AG",
      loaiDoiTuong: "Sinh viên",
      chieu: "Hai chiều",
      hanNopHoSo: "2025-04-15",
      ngayCongBo: "2025-03-01",
      trangThaiCt: "Đang mở",
      soSuatToiDa: 10,
      kinhPhiHt: 500000000,
      loaiXetDuyet: "QTSV-TCB",
  },
  {
      maCtTraoDoi: "CTTCB-2025-002",
      tenCtTraoDoi: "Trao đổi GV Nghiên cứu Y",
      doiTacChinh: "NUS",
      loaiDoiTuong: "Giảng viên",
      chieu: "Hai chiều",
      hanNopHoSo: "2025-07-30",
      ngayCongBo: "2025-06-01",
      trangThaiCt: "Đang mở",
      soSuatToiDa: 2,
      kinhPhiHt: 200000000,
      loaiXetDuyet: "QTGV-NC",
  },
  {
      maCtTraoDoi: "CTTCB-2024-005",
      tenCtTraoDoi: "Trao đổi SV Ngắn hạn CNTT",
      doiTacChinh: "IBM",
      loaiDoiTuong: "Sinh viên",
      chieu: "Đi",
      hanNopHoSo: "2024-10-01",
      ngayCongBo: "2024-08-15",
      trangThaiCt: "Đã đóng",
      soSuatToiDa: 5,
      kinhPhiHt: 150000000,
      loaiXetDuyet: "QTSV-TCB",
  },
  {
      maCtTraoDoi: "CTTCB-2025-006",
      tenCtTraoDoi: "Trao đổi NCS (Inbound)",
      doiTacChinh: "ĐH California",
      loaiDoiTuong: "Nghiên cứu sinh",
      chieu: "Đến",
      hanNopHoSo: "2025-09-15",
      ngayCongBo: "2025-07-01",
      trangThaiCt: "Đang mở",
      soSuatToiDa: 3,
      kinhPhiHt: 0,
      loaiXetDuyet: "QT_INBOUND",
  },
]


export const mockDataButtonModal: IAssignmentOfApprovalButtonModalInfoViewModel[] = [
  {
      maBuocXetDuyet: "BXD001",
      maLoaiXetDuyet: "QTSV-TCB",
      thuTu: 1,
      tenBuocXetDuyet: "Sáng lọc ban đầu",
      donViPhuTrach: "Phòng HTQT",
      loaiTieuChi: "Điểm/Nhận xét",
      thangDiemToiDa: 10,
      ghiChu: "Kiểm tra tính đầy đủ và hợp lệ của hồ sơ.",
      trangThaiHoSo: "Đang sáng lọc",
      phuTrach: "Tô Ngọc Linh",
  },
  {
      maBuocXetDuyet: "BXD002",
      maLoaiXetDuyet: "QTSV-TCB",
      thuTu: 2,
      tenBuocXetDuyet: "Đánh giá chuyên môn Khoa",
      donViPhuTrach: "Khoa/Viện chủ quán",
      loaiTieuChi: "Điểm/Nhận xét",
      thangDiemToiDa: 100,
      ghiChu: "Đánh giá năng lực học thuật và kế hoạch học tập.",
      trangThaiHoSo: "Chờ Khoa duyệt",
      phuTrach: "Tô Ngọc Linh",
  },
  {
      maBuocXetDuyet: "BXD003",
      maLoaiXetDuyet: "QTSV-TCB",
      thuTu: 3,
      tenBuocXetDuyet: "Phòng văn",
      donViPhuTrach: "Hội đồng tuyển sinh HTQT",
      loaiTieuChi: "Điểm/Nhận xét",
      thangDiemToiDa: 10,
      ghiChu: "Đánh giá kỹ năng mềm, ngoại ngữ, động lực.",
      trangThaiHoSo: "Đang phòng văn",
      phuTrach: "Tô Ngọc Ly",
  },
  {
      maBuocXetDuyet: "BXD004",
      maLoaiXetDuyet: "QTSV-TCB",
      thuTu: 4,
      tenBuocXetDuyet: "Phê duyệt cuối cùng",
      donViPhuTrach: "Ban Giám hiệu/Lãnh đạo trường",
      loaiTieuChi: "Quyết định cuối cùng",
      thangDiemToiDa: undefined,
      ghiChu: "Ra quyết định chấp nhận/từ chối.",
      trangThaiHoSo: "Đang chờ phê duyệt cuối cùng",
      phuTrach: "Tô Lanh",
  },
]

export const mockDataPhuTrach: string[]=[
  "Tô Ngọc Linh",
  "Tô Ngọc Ly",
  "Tô Lanh",
]