export interface ICOECourseSectionInfoViewModel {
    id?: number;
    code?: string;
    name?: string;
    concurrencyStamp?: string;
    isEnabled?: boolean;
    modifiedWhen?: string;
    modifiedBy?: number;
    modifiedFullName?: string;
    coeGradeSubjectId?: number;
    pointRecordUserId?: number;
    coeGradeSubject?: {
        id?: number;
        code?: string;
        name?: string;
        concurrencyStamp?: string;
        isEnabled?: boolean;
        modifiedWhen?: string;
        modifiedBy?: number;
        modifiedFullName?: string;
        coeGradeId?: number;
        coeSubjectId?: number;
        coeSemesterId?: number;
        coeSubjectGroupId?: number;
        order?: number | null;
        isCore?: boolean | null;
        courseSectionQuantity?: number | null;
        courseSectionQuantityActual?: number;
        teachingUnitId?: number;
        measureUnitId?: number | null;
        collectUnitId?: number | null;
        coecGs?: any[];
        coeSubjectFomulas?: any[];
        coeGrade?: any | null;
        coeSubject?: {
            id?: number;
            code?: string;
            name?: string;
            concurrencyStamp?: string;
            isEnabled?: boolean;
            modifiedWhen?: string;
            modifiedBy?: number;
            modifiedFullName?: string;
            nameEg?: string;
            numberPeriod?: number;
            numberCredit?: number;
            note?: string;
            coeUnitId?: number;
            coeUnit?: any | null;
        };
        coeSemester?: {
            id?: number;
            code?: string;
            name?: string;
            concurrencyStamp?: string;
            isEnabled?: boolean;
            modifiedWhen?: string;
            modifiedBy?: number;
            modifiedFullName?: string;
            startDate?: string;
            endDate?: string;
            coeSchoolYearId?: number;
            numberWeek?: number;
            note?: string;
            isCurrent?: boolean;
            coeSchoolYear?: any | null;
        };
        coeSubjectGroup?: any | null;
        coeSubjectAssessments?: any[];
        coeGradeSubjectMITPIs?: any[];
        teachingUnit?: any | null;
        measureUnit?: any | null;
        collectUnit?: any | null;
    };
    coeCourseSectionClass?: {
        id?: number;
        code?: string | null;
        name?: string | null;
        concurrencyStamp?: string;
        isEnabled?: boolean;
        modifiedWhen?: string;
        modifiedBy?: number;
        modifiedFullName?: string;
        coeCourseSectionId?: number;
        coeClassId?: number;
        coeClass?: {
            id?: number;
            code?: string | null;
            name?: string | null;
            concurrencyStamp?: string;
            isEnabled?: boolean;
            modifiedWhen?: string;
            modifiedBy?: number;
            modifiedFullName?: string;
            coeGradeId?: number;
            order?: number | null;
            note?: string;
        }
    }[];
    pointRecordUser?: {
        id?: number;
        code?: string;
        email?: string;
        phoneNumber?: string;
        address?: string;
        avatarPath?: string;
        fullName?: string;
        gender?: number;
        dateOfBirth?: string;
        modifiedBy?: number;
        modifiedWhen?: string;
        coeClassId?: number | null;
        coeClass?: any | null;
    };
    studentQuantity?: number;
    studyGroup?: string;
}
