export interface ICourseSectionClassViewModel {
    id?: number;
    code?: string;
    name?: string;
    concurrencyStamp?: string;
    isEnabled?: boolean;
    modifiedWhen?: string;
    modifiedBy?: number;
    coeCourseSectionId?: number;
    coeClassId?: number;
}

export interface ICOEGradeSubjectViewModel {
    id?: number;
    code?: string;
    name?: string;
    coeGradeId?: number;
    coeSubjectId?: number;
    coeSemesterId?: number;
    coeSubjectGroupId?: number;
    order?: number;
    isCore?: boolean;
    courseSectionQuantity?: number;
    courseSectionQuantityActual?: number;
    concurrencyStamp?: string;
    isEnabled?: boolean;
    modifiedWhen?: string;
    modifiedBy?: number;
    modifiedFullName?: string;
    coecGs?: any[];
    coeSubjectFomulas?: any[];
    coeGrade?: {
        id?: number;
        code?: string;
        name?: string;
        coeSemesterStartId?: number;
        coeSemesterEndId?: number;
        coeTrainingLevelId?: number;
        coeProgramId?: number;
        note?: string;
        isActive?: boolean;
        totalSubject?: number;
        totalCredit?: number;
        coeDegreeLevelId?: number | null;
        concurrencyStamp?: string;
        isEnabled?: boolean;
        modifiedWhen?: string;
        modifiedBy?: number;
        modifiedFullName?: string;
        coeSemesterStart?: {
            id?: number;
            code?: string;
            name?: string;
            startDate?: string;
            endDate?: string;
            coeSchoolYearId?: number;
            numberWeek?: number;
            note?: string;
            isCurrent?: boolean;
            concurrencyStamp?: string;
            isEnabled?: boolean;
            modifiedWhen?: string;
            modifiedBy?: number;
            modifiedFullName?: string;
            coeSchoolYear?: any | null;
        };
        coeSemesterEnd?: any | null;
        coeTrainingLevel?: any | null;
        coeProgram?: any | null;
        coeDegreeLevel?: any | null;
    };
    coeSubject?: {
        id?: number;
        code?: string;
        name?: string;
        nameEg?: string;
        numberPeriod?: number;
        numberCredit?: number;
        note?: string;
        coeUnitId?: number;
        coeUnit?: any | null;
        concurrencyStamp?: string;
        isEnabled?: boolean;
        modifiedWhen?: string;
        modifiedBy?: number;
        modifiedFullName?: string;
    };
    coeSemester?: {
        id?: number;
        code?: string;
        name?: string;
        startDate?: string;
        endDate?: string;
        coeSchoolYearId?: number;
        numberWeek?: number;
        note?: string;
        isCurrent?: boolean;
        coeSchoolYear?: any | null;
        concurrencyStamp?: string;
        isEnabled?: boolean;
        modifiedWhen?: string;
        modifiedBy?: number;
        modifiedFullName?: string;
    };
    coeSubjectGroup?: any | null;
    coeSubjectAssessments?: any[];
    coeGradeSubjectMITPIs?: any[];
}

export interface IClassInfoViewModel {
    order?: number | null;
    coeGradeId?: number;
    note?: string | null;
    totalStudent?: number;
    coeGrade?: {
        coeSemesterStartId?: number;
        coeSemesterEndId?: number;
        coeTrainingLevelId?: number;
        coeProgramId?: number;
        note?: string;
        isActive?: boolean;
        totalSubject?: number;
        totalCredit?: number;
        coeDegreeLevelId?: number | null;
        coeSemesterStart?: any | null;
        coeSemesterEnd?: any | null;
        coeTrainingLevel?: any | null;
        coeProgram?: any | null;
        coeDegreeLevel?: any | null;
        id?: number;
        code?: string;
        name?: string;
        concurrencyStamp?: string;
        isEnabled?: boolean;
        modifiedWhen?: string;
        modifiedBy?: number;
        modifiedFullName?: string;
    };
    users?: any[];
    id?: number;
    code?: string;
    name?: string;
    concurrencyStamp?: string;
    isEnabled?: boolean;
    modifiedWhen?: string;
    modifiedBy?: number;
    modifiedFullName?: string;
}

export interface ILecturer {
    teachingStatus?: null | string;
    userBranch?: any[];
    branchs?: any[];
    userSkillCenters?: any[];
    userPrograms?: any[];
    id?: number;
    isBlocked?: boolean;
    roleId?: number;
    userName?: string;
    code?: string;
    email?: string;
    phoneNumber?: string;
    address?: string;
    avatarPath?: string;
    fullName?: string;
    facultyId?: number;
    facultyName?: null | string;
    classId?: null | number;
    majorsId?: null | number;
    workingUnitId?: null | number;
    workingUnitName?: null | string;
    gender?: number;
    dateOfBirth?: string;
    educationLevel?: number;
    modifiedBy?: number;
    coeClassId?: null | number;
    modifiedWhen?: string;
    roles?: any[];
}
