import { IButtonModalInfoViewModel } from "./ButtonModalProfileConfiguration/ButtonModalProfileConfiguration";
import { IRequiredDocumentsForRegistrationReadInfoViewModel } from "./RequiredDocumentsForRegistrationRead";

export const mockDataRead: IRequiredDocumentsForRegistrationReadInfoViewModel[] = [
  {
    maCtTraoDoi: "CTTCB-2025-001",
    tenCtTraoDoi: "Chương trình Trao đổi SV Kỹ thuật",
    doiTacChinh: "Siemens AG",
    lopDoiTuong: "Sinh viên",
    chieu: "Hai chiều",
    hanNopHoSo: "2025-04-15",
    ngayCongBo: "2025-03-01",
    trangThaiCt: "Đang mở",
    soSuatToiDa: 10,
    kinhPhiHt: 500000000,
  },
  {
    maCtTraoDoi: "CTTCB-2025-002",
    tenCtTraoDoi: "Trao đổi GV Nghiên cứu Y",
    doiTacChinh: "NUS",
    lopDoiTuong: "Giảng viên",
    chieu: "Hai chiều",
    hanNopHoSo: "2025-07-30",
    ngayCongBo: "2025-06-01",
    trangThaiCt: "Đang mở",
    soSuatToiDa: 2,
    kinhPhiHt: 200000000,
  },
  {
    maCtTraoDoi: "CTTCB-2024-005",
    tenCtTraoDoi: "Trao đổi SV Ngắn hạn CNTT",
    doiTacChinh: "IBM",
    lopDoiTuong: "Sinh viên",
    chieu: "Đi",
    hanNopHoSo: "2024-10-01",
    ngayCongBo: "2024-08-15",
    trangThaiCt: "Đã đóng",
    soSuatToiDa: 5,
    kinhPhiHt: 150000000,
  },
  {
    maCtTraoDoi: "CTTCB-2025-006",
    tenCtTraoDoi: "Trao đổi NCS (Inbound)",
    doiTacChinh: "ĐH California",
    lopDoiTuong: "Nghiên cứu sinh",
    chieu: "Đến",
    hanNopHoSo: "2025-09-15",
    ngayCongBo: "2025-07-01",
    trangThaiCt: "Đang mở",
    soSuatToiDa: 3,
    kinhPhiHt: 0,
  },
];

export const mockDataButtonModal: IButtonModalInfoViewModel[] = [
  {
    maSoHoso: "YCH001",
    tenHoso: "CV (Curriculum Vitae)",
    batBuoc: true,
    moTaChiTiet: "Sơ yếu lý lịch tự thuật, nêu rõ kinh nghiệm học tập, làm việc, kỹ năng, và dự định sau trao đổi.",
    dinhDangChoPhep: ["PDF"],
    ghiChuHuongDan: "Tối đa 2 trang A4.",
  },
  {
    maSoHoso: "YCH002",
    tenHoso: "Bảng điểm có xác nhận của trường",
    batBuoc: true,
    moTaChiTiet: "Bảng điểm các học kỳ đã học, tính đến thời điểm nộp hồ sơ.",
    dinhDangChoPhep: ["PDF"],
    ghiChuHuongDan: "Có dấu của Phòng Đào tạo.",
  },
  {
    maSoHoso: "YCH003",
    tenHoso: "Thư giới thiệu",
    batBuoc: true,
    moTaChiTiet: "Tối thiểu 1 thư giới thiệu từ giảng viên hướng dẫn hoặc người quản lý trực tiếp.",
    dinhDangChoPhep: ["PDF"],
    ghiChuHuongDan: "Có đầy đủ chữ ký và thông tin liên hệ của người giới thiệu.",
  },
  {
    maSoHoso: "YCH004",
    tenHoso: "Chứng chỉ ngoại ngữ",
    batBuoc: true,
    moTaChiTiet: "IELTS (tối thiểu 6.5) hoặc TOEFL iBT (tối thiểu 90), còn hiệu lực.",
    dinhDangChoPhep: ["PDF"],
    ghiChuHuongDan: "Nộp bản scan gốc.",
  },
  {
    maSoHoso: "YCH005",
    tenHoso: "Kế hoạch học tập/làm việc chi tiết",
    batBuoc: true,
    moTaChiTiet: "Kế hoạch chi tiết các môn học/hoạt động dự kiến tham gia tại Siemens AG.",
    dinhDangChoPhep: ["PDF"],
    ghiChuHuongDan: "Nêu rõ mục tiêu, lộ trình và kết quả mong muốn.",
  },
  {
    maSoHoso: "YCH006",
    tenHoso: "Bản sao hộ chiếu",
    batBuoc: false,
    moTaChiTiet: "Bản sao trang thông tin có ảnh của hộ chiếu còn hạn sử dụng.",
    dinhDangChoPhep: ["PDF", "JPG"],
    ghiChuHuongDan: "Để phục vụ việc làm visa sau này.",
  },
];
