import { IPerformIPtasksInfoViewModel } from "./F_ReadPerformIPtasks";

export const mockDataRead: IPerformIPtasksInfoViewModel[] = [
  {
    maIp: "IP-SC-2024-002",
    tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
    buocTrongQuyTrinh: "1. Tiếp nhận hồ sơ nội bộ",
    ngayBatDauBuoc: "2023-02-20",
    ngayKetThucBuocNgaySuKien: "2023-02-28",
    moTaGhiChuChiTiet: "Chuẩn bị và kiểm tra hồ sơ sơ bộ.",
    tenTaiLieu: "Bảng độc quyền sáng chế",
    loaiTaiLieu: "Văn bằng bảo hộ",
    fileMinhChung: "Xem file",
    trangThaiCuaBuoc: "Hoàn thành",
  },
  {
    maIp: "IP-SC-2024-002",
    tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
    buocTrongQuyTrinh: "2. Nộp đơn chính thức",
    ngayBatDauBuoc: "2023-03-01",
    ngayKetThucBuocNgaySuKien: "2023-03-01",
    moTaGhiChuChiTiet: "Hồ sơ đã được nộp tại Cục SHTT.",
    tenTaiLieu: "Bảng độc quyền sáng chế",
    loaiTaiLieu: "Văn bằng bảo hộ",
    fileMinhChung: "Xem file",
    trangThaiCuaBuoc: "Hoàn thành",
  },
  {
    maIp: "IP-SC-2024-002",
    tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
    buocTrongQuyTrinh: "3. Thẩm định hình thức",
    ngayBatDauBuoc: "2023-03-05",
    ngayKetThucBuocNgaySuKien: "2023-04-15",
    moTaGhiChuChiTiet: "Cục SHTT kiểm tra tính hợp lý về hình thức.",
    tenTaiLieu: "Bảng độc quyền sáng chế",
    loaiTaiLieu: "Văn bằng bảo hộ",
    fileMinhChung: "Xem file",
    trangThaiCuaBuoc: "Hoàn thành",
  },
  {
    maIp: "IP-SC-2024-002",
    tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
    buocTrongQuyTrinh: "4. Công bố đơn",
    ngayBatDauBuoc: "2023-05-20",
    ngayKetThucBuocNgaySuKien: "2023-05-20",
    moTaGhiChuChiTiet: "Đơn đã được công bố trên Công báo SHTT số 450.",
    tenTaiLieu: "Bảng độc quyền sáng chế",
    loaiTaiLieu: "Văn bằng bảo hộ",
    fileMinhChung: "Xem file",
    trangThaiCuaBuoc: "Hoàn thành",
  },
  {
    maIp: "IP-SC-2024-002",
    tenIp: "Thuật toán nhận dạng khuôn mặt bằng AI",
    buocTrongQuyTrinh: "5. Thẩm định nội dung",
    ngayBatDauBuoc: "2023-06-01",
    ngayKetThucBuocNgaySuKien: "2024-11-15",
    moTaGhiChuChiTiet: "Quá trình thẩm định về tính mới, trình độ sáng tạo, khả năng áp dụng công nghiệp.",
    tenTaiLieu: "Bảng độc quyền sáng chế",
    loaiTaiLieu: "Văn bằng bảo hộ",
    fileMinhChung: "Xem file",
    trangThaiCuaBuoc: "Đang xử lý",
  },
];

export const mockDataTrangThai: string[] = ["Hoàn thành", "Đang xử lý"];
