import { I_TuitionFee } from "./interfaces";

export const mockData_TuitionFee: I_TuitionFee[] = [
  {
    programCode: "LTW",
    programName: "Lập trình website",
    price: 1550000,
    note: "Giá niêm yết chung cho chương trình",
  },
  {
    programCode: "LTW",
    programName: "Lập trình website",
    campusCode: "TD",
    campusName: "Khu Công nghệ cao Thủ Đức",
    price: 1250000,
    note: "Giá áp dụng riêng tại cơ sở Thủ Đức",
  },
  {
    programCode: "LTW",
    programName: "Lập trình website",
    campusCode: "TD",
    campusName: "Khu Công nghệ cao Thủ Đức",
    courseSectionCode: "LTW23",
    courseSectionName: "Lập trình website khóa 2023",
    price: 1150000,
    note: "Giá ưu đãi cho khóa đầu tiên tại cơ sở mới",
  },
  {
    programCode: "TOAN_K7",
    programName: "Chương trình Bồi dưỡng Toán Khối 7",
    campusCode: "CS1",
    campusName: "Cơ sở 1",
    levelCode: "TOAN_K7_A",
    levelName: "Toán Khối 7 - Cấp độ A",
    price: 7000000,
    note: "Áp dụng cho học kỳ 1 năm học 2024-2025",
  },
  {
    programCode: "TOAN_K7",
    programName: "Chương trình Bồi dưỡng Toán Khối 7",
    campusCode: "CS1",
    campusName: "Cơ sở 1",
    levelCode: "TOAN_K7_B",
    levelName: "Toán Khối 7 - Cấp độ B",
    price: 7000000,
    note: "Áp dụng cho học kỳ 2 năm học 2024-2025",
  },
  {
    programCode: "TA_TQ",
    programName: "Tiếng Anh Tổng Quát",
    campusCode: "CS2",
    campusName: "Cơ sở 2",
    levelCode: "TA_TQ_A1",
    levelName: "Tiếng Anh Tổng Quát - Cấp độ A1",
    price: 1500000,
    note: "Chương trình tiếng Anh cho người mới bắt đầu",
  },
];
