import { IQuestionReviewInfoViewModel } from "./interfaces/QuestionReviewViewModel";

export const mockDataRead: IQuestionReviewInfoViewModel[] = [
    {
        maCauHoi: "CH0001",
        noiDungCauHoi: "Trong mô hình CSDL quan hệ, một bảng (table) là một tập hợp các...",
        loaiCauHoi: "Trắc nghiệm (1 đáp án)",
        soDapAn: 4,
        maChuong: "C1",
        chuongChuDe: "Chủ đề 1: Khái niệm CSDL",
        doKho: "Dễ",
        mucDoNhanThuc: "Ghi nhớ",
        clo: "CLO1",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0002",
        noiDungCauHoi: "SQL là viết tắt của thuật ngữ nào?",
        loaiCauHoi: "Trắc nghiệm (Nhiều đáp án)",
        soDapAn: 4,
        maChuong: "C1",
        chuongChuDe: "Chủ đề 1: Khái niệm CSDL",
        doKho: "Dễ",
        mucDoNhanThuc: "Ghi nhớ",
        clo: "CLO1",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0003",
        noiDungCauHoi: "Trong cơ sở dữ liệu quan hệ để tạo một bảng mới ta sử dụng lệnh _________",
        loaiCauHoi: "Điền khuyết",
        soDapAn: 1,
        maChuong: "C2",
        chuongChuDe: "Chủ đề 2: DDL",
        doKho: "Trung bình",
        mucDoNhanThuc: "Hiểu",
        clo: "CLO3",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0004",
        noiDungCauHoi: "Khóa chính (Primary Key) phải là _______ và ________",
        loaiCauHoi: "Điền khuyết",
        soDapAn: 2,
        maChuong: "C1",
        chuongChuDe: "Chủ đề 1: Khái niệm Khóa",
        doKho: "Trung bình",
        mucDoNhanThuc: "Hiểu",
        clo: "CLO2",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0005",
        noiDungCauHoi: "Nối mỗi thuật ngữ bên trái với định nghĩa phù hợp bên phải",
        loaiCauHoi: "Ghép nối",
        soDapAn: 1,
        maChuong: "C1",
        chuongChuDe: "Chủ đề 1: Khái niệm CSDL",
        doKho: "Trung bình",
        mucDoNhanThuc: "Hiểu",
        clo: "CLO2",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0006",
        noiDungCauHoi: "Hãy giải thích sự khác biệt cơ bản giữa mô hình CSDL quan hệ (Relational Database) và mô hình CSDL NoSQL (Non-relational Database). Nếu ví dụ về trường hợp sử dụng phù hợp cho mỗi loại.",
        loaiCauHoi: "Tự luận",
        soDapAn: 1,
        maChuong: "C4",
        chuongChuDe: "Chủ đề 1: Khái niệm CSDL",
        doKho: "Khó",
        mucDoNhanThuc: "Phân tích",
        clo: "CLO4",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0007",
        noiDungCauHoi: "Cho lược đồ quan hệ: SinhVien (MaSV, TenSV, NgaySinh, MaKhoa) và Khoa (MaKhoa, TenKhoa). Viết các câu lệnh SQL để: a) Thêm một sinh viên mới. b) Cập nhật tên khoa của sinh viên. c) Liệt kê tất cả sinh viên thuộc khoa \"Công nghệ thông tin\".",
        loaiCauHoi: "Tự luận",
        soDapAn: 1,
        maChuong: "C2",
        chuongChuDe: "Chủ đề 2: DMLL",
        doKho: "Khó",
        mucDoNhanThuc: "Phân tích",
        clo: "CLO3",
        trangThai: "Chờ duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0008",
        noiDungCauHoi: "Tổ chức ngắn gọn ý nghĩa và mối liên quan trong việc chuẩn hóa dữ liệu (Normalization) trong thiết kế cơ sở dữ liệu. Bạn có thể nêu ví dụ minh họa cho các cấp độ chuẩn hóa (1NF, 2NF, 3NF) nếu muốn.",
        loaiCauHoi: "Viết",
        soDapAn: 1,
        maChuong: "C3",
        chuongChuDe: "Chủ đề 3: Chuẩn hóa",
        doKho: "Rất khó",
        mucDoNhanThuc: "Phân tích",
        clo: "CLO5",
        trangThai: "Không duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    },
    {
        maCauHoi: "CH0009",
        noiDungCauHoi: "Trong mô hình CSDL quan hệ; một bảng (table) là một tập hợp các...",
        loaiCauHoi: "Viết",
        soDapAn: 1,
        maChuong: "C1",
        chuongChuDe: "Chủ đề 1: Khái niệm CSDL",
        doKho: "Dễ",
        mucDoNhanThuc: "Ghi nhớ",
        clo: "CLO1",
        trangThai: "Đã duyệt",
        ngayDuyet: undefined,
        nguoiDuyet: undefined,
        noiDungDuyet: undefined
    }
];
