import { ISummaryOfExchangeResultsInfoViewModel } from "./SummaryOfExchangeResultsRead";

export const mockData: ISummaryOfExchangeResultsInfoViewModel[] = [
  {
    maLuatTraoDoi: "LTTC-2025-001",
    maHaSo: "HSXT-2025-001",
    maNguoiDung: "SV001",
    chieuTraoDoi: "Đi",
    thoiGianBatDau: "2025-09-01",
    thoiGianKetThuc: "2026-02-28",
    trangThaiLuotTraoDoi: "Đã hoàn thành",
    ghiChuTrangThaiCuoi: "Hoàn tất chương trình và báo cáo đầy đủ",
    coVanDe: "Không",
  },
  {
    maLuatTraoDoi: "LTTC-2025-002",
    maHaSo: "HSXT-2025-003",
    maNguoiDung: "SV002",
    chieuTraoDoi: "Đi",
    thoiGianBatDau: "2025-11-15",
    thoiGianKetThuc: "2026-02-15",
    trangThaiLuotTraoDoi: "Đã hoàn thành",
    ghiChuTrangThaiCuoi: "Báo cáo đã được duyệt.",
    coVanDe: "Không",
  },
  {
    maLuatTraoDoi: "LTTC-2025-005",
    maHaSo: "HSXT-2025-010",
    maNguoiDung: "SV005",
    chieuTraoDoi: "Đi",
    thoiGianBatDau: "2025-09-01",
    thoiGianKetThuc: "2026-02-28",
    trangThaiLuotTraoDoi: "Đã kết thúc (Chưa nộp báo cáo)",
    ghiChuTrangThaiCuoi: "Đã gọi 2 email nhắc nhở nhưng SV chưa phản hồi.",
    coVanDe: "Có",
  },
  {
    maLuatTraoDoi: "LTTC-2025-006",
    maHaSo: "HSXT-2025-011",
    maNguoiDung: "SV006",
    chieuTraoDoi: "Đi",
    thoiGianBatDau: "2025-10-01",
    thoiGianKetThuc: "2026-03-31",
    trangThaiLuotTraoDoi: "Báo cáo chưa hoàn thiện",
    ghiChuTrangThaiCuoi: 'Báo cáo nộp thiếu mục "Kế hoạch hưởng lợi", đã yêu cầu chỉnh sửa',
    coVanDe: "Có",
  },
  {
    maLuatTraoDoi: "LTTC-2025-007",
    maHaSo: "HSXT-2025-012",
    maNguoiDung: "SV007",
    chieuTraoDoi: "Đi",
    thoiGianBatDau: "2025-09-15",
    thoiGianKetThuc: "2026-01-15",
    trangThaiLuotTraoDoi: "Đã hủy (Giữa chừng)",
    ghiChuTrangThaiCuoi: "SV về nước sớm do vấn đề sức khỏe cá nhân.",
    coVanDe: "Có",
  },
  {
    maLuatTraoDoi: "LTTC-2025-008",
    maHaSo: "HSXT-2025-013",
    maNguoiDung: "SV008",
    chieuTraoDoi: "Đến",
    thoiGianBatDau: "2025-08-01",
    thoiGianKetThuc: "2025-12-01",
    trangThaiLuotTraoDoi: "Đã hủy (Vì phạm)",
    ghiChuTrangThaiCuoi: "SV bị đình chỉ học do vi phạm quy chế tại trường.",
    coVanDe: "Có",
  },
  {
    maLuatTraoDoi: "LTTC-2025-009",
    maHaSo: "HSXT-2025-014",
    maNguoiDung: "SV009",
    chieuTraoDoi: "Đi",
    thoiGianBatDau: "2025-09-01",
    thoiGianKetThuc: "2026-02-28",
    trangThaiLuotTraoDoi: "Đang diễn ra",
    ghiChuTrangThaiCuoi: undefined,
    coVanDe: "Không",
  },
];

export const mockDataTrangThai: string[] = [
  "Đã hoàn thành",
  "Đã kết thúc (Chưa nộp báo cáo)",
  "Báo cáo chưa hoàn thiện",
  "Đã hủy (Giữa chừng)",
  "Đã hủy (Vì phạm)",
  "Đang diễn ra",
];
