import { IInfoViewModel } from "./F9_8_9ReadExchangeReport";

export const mockDataRead: IInfoViewModel[] = [
  {
    maBaoCao: "BCKQ-001",
    maLuotTraoDoi: "LTTC-2025-001",
    maNguoiDung: "SV001",
    ngayNopBaoCao: "2026-03-05",
    tomTatKetQua: "Hoàn thành tất các môn học, tham gia dự án tự động hội.",
    fileDinhKem: "Xem file",
    danhGiaTongQuan: "Xuất sắc, vượt mong đợi",
    trangThaiBaoCao: "Đã duyệt",
    nguoiDuyetBaoCao: "CB001 (Phạm Thị Gầm)",
    ngayDuyetBaoCao: "2026-03-15",
    ghiChu: "Báo cáo đạt yêu cầu và đã được phê duyệt.",
  },
  {
    maBaoCao: "BCKQ-002",
    maLuotTraoDoi: "LTTC-2025-005",
    maNguoiDung: "SV005",
    ngayNopBaoCao: undefined,
    tomTatKetQua: undefined,
    fileDinhKem: undefined,
    danhGiaTongQuan: undefined,
    trangThaiBaoCao: "Chờ nộp",
    nguoiDuyetBaoCao: undefined,
    ngayDuyetBaoCao: undefined,
    ghiChu: "Người tham gia chưa nộp báo cáo. Đã gọi trao đổi.",
  },
  {
    maBaoCao: "BCKQ-003",
    maLuotTraoDoi: "LTTC-2025-006",
    maNguoiDung: "SV006",
    ngayNopBaoCao: "2026-04-01",
    tomTatKetQua: "Các hoạt động đã tham gia, một số khó khăn ban đầu.",
    fileDinhKem: "Xem file",
    danhGiaTongQuan: "Tất",
    trangThaiBaoCao: "Yêu cầu chỉnh sửa",
    nguoiDuyetBaoCao: "CB001 (Phạm Thị Gầm)",
    ngayDuyetBaoCao: "2026-04-10",
    ghiChu: "Báo cáo thiếu thông tin và kế hoạch sau trao đổi.",
  },
  {
    maBaoCao: "BCKQ-004",
    maLuotTraoDoi: "LTTC-2025-007",
    maNguoiDung: "SV007",
    ngayNopBaoCao: "2026-01-20",
    tomTatKetQua: "Tóm tắt quá trình học tập ngắn hạn tự đối tác.",
    fileDinhKem: "Xem file",
    danhGiaTongQuan: "Tạm ổn",
    trangThaiBaoCao: "Đã huỷ (Không áp dụng)",
    nguoiDuyetBaoCao: "CB001 (Phạm Thị Gầm)",
    ngayDuyetBaoCao: "2026-01-25",
    ghiChu: "Lượt trao đổi bị huỷ do lý do sức khỏe.",
  },
  {
    maBaoCao: "BCKQ-005",
    maLuotTraoDoi: "LTTC-2025-008",
    maNguoiDung: "SV008",
    ngayNopBaoCao: undefined,
    tomTatKetQua: undefined,
    fileDinhKem: undefined,
    danhGiaTongQuan: undefined,
    trangThaiBaoCao: "Đã huỷ (Vi phạm)",
    nguoiDuyetBaoCao: undefined,
    ngayDuyetBaoCao: undefined,
    ghiChu: "Lượt trao đổi bị huỷ do SV vi phạm quy định.",
  },
];

export const mockDataTrangThaiBaoCao: string[] = [
  "Chờ nộp",
  "Đã duyệt",
  "Yêu cầu chỉnh sửa",
  "Đã huỷ (Không áp dụng)",
  "Đã huỷ (Vi phạm)",
];

export const mockDataNguoiDuyetBaoCao: string[] = [
  "CB001 (Phạm Thị Gầm)",
  "CB002 (Nguyễn Văn A)",
  "CB003 (Trần Thị B)",
  "CB004 (Lê Văn C)",
];
