import { Ikfjughenth } from "./F_kfjughenth_Read";

export const mockDataRead: Ikfjughenth[] = [
    {
        maHocVien: "HV0001",
        hoTen: "Nguyễn Văn An",
        gioiTinh: "Nam",
        ngaySinh: "1990-01-01",
        soDienThoai: "0896585235",
        email: "a@gmail.com",
        maKhoaHoc: "DGT2401",
        tenKhoaHoc: "Digital marketing 2024",
        cumThoiGian: "Tối 2 4 6",
        chiNhanh: "Thủ Đức",
        loaiQuyetDinh: "Bảo lưu",
    },
    {
        maHocVien: "HV0002",
        hoTen: "Nguyễn Văn Bình",
        gioiTinh: "Nam",
        ngaySinh: "1990-01-01",
        soDienThoai: "0896585235",
        email: "a@gmail.com",
        maKhoaHoc: "DGT2401",
        tenKhoaHoc: "Digital marketing 2024",
        cumThoiGian: "Tối 2 4 6",
        chiNhanh: "Thủ Đức",
        loaiQuyetDinh: "Buộc thôi học",
        ngayQuyetDinh: undefined,
        tenQuyetDinh: undefined,
        ghiChu: undefined,
        minhChungQuyetDinh: "minhChung.pdf",
        bienLaiChuyenKhoan: "bienLai.pdf",
        huyQuyetDinh: false
    },
    {
        maHocVien: "HV0003",
        hoTen: "Nguyễn Văn Bảo",
        gioiTinh: "Nam",
        ngaySinh: "1990-01-01",
        soDienThoai: "0896585235",
        email: "a@gmail.com",
        maKhoaHoc: "DGT2401",
        tenKhoaHoc: "Digital marketing 2024",
        cumThoiGian: "Tối 2 4 6",
        chiNhanh: "Thủ Đức",
        loaiQuyetDinh: "Nhập học lại",
        ngayQuyetDinh: undefined,
        tenQuyetDinh: undefined,
        ghiChu: undefined,
        minhChungQuyetDinh: "minhChung.pdf",
        bienLaiChuyenKhoan: "bienLai.pdf",
        huyQuyetDinh: false
    },
    {
        maHocVien: "HV0004",
        hoTen: "Nguyễn Văn Linh",
        gioiTinh: "Nam",
        ngaySinh: "1990-01-01",
        soDienThoai: "0896585235",
        email: "a@gmail.com",
        maKhoaHoc: "DGT2401",
        tenKhoaHoc: "Digital marketing 2024",
        cumThoiGian: "Tối 2 4 6",
        chiNhanh: "Thủ Đức",
        loaiQuyetDinh: "Rút đăng ký",
        ngayQuyetDinh: undefined,
        tenQuyetDinh: undefined,
        ghiChu: undefined,
        minhChungQuyetDinh: "minhChung.pdf",
        bienLaiChuyenKhoan: "bienLai.pdf",
        huyQuyetDinh: false
    },
    {
        maHocVien: "HV0005",
        hoTen: "Nguyễn Văn Long",
        gioiTinh: "Nam",
        ngaySinh: "1990-01-01",
        soDienThoai: "0896585235",
        email: "a@gmail.com",
        maKhoaHoc: "DGT2401",
        tenKhoaHoc: "Digital marketing 2024",
        cumThoiGian: "Tối 2 4 6",
        chiNhanh: "Thủ Đức",
        loaiQuyetDinh: "Chuyển khóa học",
        ngayQuyetDinh: undefined,
        tenQuyetDinh: undefined,
        ghiChu: undefined,
        minhChungQuyetDinh: "minhChung.pdf",
        bienLaiChuyenKhoan: "bienLai.pdf",
        huyQuyetDinh: false
    },
    {
        maHocVien: "HV0006",
        hoTen: "Nguyễn Văn Huy",
        gioiTinh: "Nam",
        ngaySinh: "1990-01-01",
        soDienThoai: "0896585235",
        email: "a@gmail.com",
        maKhoaHoc: "DGT2401",
        tenKhoaHoc: "Digital marketing 2024",
        cumThoiGian: "Tối 2 4 6",
        chiNhanh: "Thủ Đức",
        loaiQuyetDinh: "Buộc thôi học",
        ngayQuyetDinh: undefined,
        tenQuyetDinh: undefined,
        ghiChu: undefined,
        minhChungQuyetDinh: "minhChung.pdf",
        bienLaiChuyenKhoan: "bienLai.pdf",
        huyQuyetDinh: true
    },
]